### ISSUE TITLE
Rule suggestion: `function-no-deprecated`

### ISSUE THREAD

**Issue by FloEdelmann** [stylelint-scss/stylelint-scss#1053]
There are some deprecated functions in Sass, see e.g. https://sass-lang.com/documentation/modules/color/#deprecated-functions.

Building code using those deprecated functions with the Sass compiler emits a deprecation warning, but reporting it already with Stylelint would be helpful while writing.

To implement it, we could split the arrays in [`src/utils/functions.js`](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/utils/functions.js), similar to:

```js
const COLOR_FUNCTIONS = Object.freeze([
  // all non-deprecated color functions
]);
const DEPRECATED_COLOR_FUNCTIONS = Object.freeze([
  // all deprecated color functions
]);

// …

const ALL_FUNCTIONS = Object.freeze([
  ...COLOR_FUNCTIONS,
  ...DEPRECATED_COLOR_FUNCTIONS,
  // …
]);

const DEPRECATED_FUNCTIONS = Object.freeze([
  ...DEPRECATED_COLOR_FUNCTIONS,
  // …
]);
```

**Comment by FloEdelmann** [comment]
Since only color functions are deprecated, maybe this rule is too broad. We could split it into separate rules:

### `function-prefer-color-adjust`

suggests using `color.adjust` / `adjust-color` instead of deprecated `adjust-hue`

### `function-prefer-color-scale`

suggests using `color.scale` / `scale-color` or `color.adjust` / `adjust-color` instead of deprecated

* `darken`
* `desaturate`
* `lighten`
* `opacify` / `fade-in`
* `color.saturate` / `saturate`
* `transparentize` / `fade-out`

### `function-prefer-color-channel`

suggests using `color.channel` instead of deprecated

* `color.alpha` / `alpha` / `opacity`
* `color.blackness` / `blackness`
* `color.blue` / `blue`
* `color.green` / `green`
* `color.hue` / `hue`
* `color.lightness` / `lightness`
* `color.red` / `red`
* `color.saturation` / `saturation`
* `color.whiteness`

**Comment by kristerkari** [comment]
I just wanted to point out that we also already have the `function-color-relative` rule https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/function-color-relative/README.md

**Comment by FloEdelmann** [comment]
Oh, thanks for mentioning that rule! That is basically what I suggested as `function-prefer-color-scale`.

**Comment by FloEdelmann** [comment]
I opened separate issues for the two remaining rule suggestions, so this issue can be closed.
