### ISSUE TITLE
Rule suggestion: `no-import`

### ISSUE THREAD

**Issue by qucumbah** [stylelint-scss/stylelint-scss#1078]
Hi, our team is currently migrating from `@import` at-rule to `@use` and `@forward` due to import's deprecation and upcoming removal in SASS 3.x.
We'd like to have an automated way to dissuade the other developers coming to our codebase from using the outdated declaration, for which we want to use this new linter rule.

I've created a pull request with the necessary changes, please take a look at it when you have the time 🫶
https://github.com/stylelint-scss/stylelint-scss/pull/1077

**Comment by kristerkari** [comment]
Thanks for opening the issue, please see the question that I posted in the PR:
https://github.com/stylelint-scss/stylelint-scss/pull/1077#issuecomment-2468908058

**Comment by qucumbah** [comment]
Closing due to existing rule `at-rule-disallowed-list `, thanks @kristerkari!
