### ISSUE TITLE
Add a lint to ban specific built-in functions

### ISSUE THREAD

**Issue by nex3** [stylelint-scss/stylelint-scss#422]
The random() function exists primarily for Sass demos to produce cool effects—it's pretty much always a bad idea to use in real stylesheets. We should add an (off-by-default) lint to forbid this function, whether from the global namespace or from `sass:math`.

cc @rambleraptor

**Comment by nex3** [comment]
Maybe a more general way to do this would be to have a lint that just takes a list of banned functions.

**Comment by kristerkari** [comment]
Would this rule from stylelint be enough? https://github.com/stylelint/stylelint/blob/master/lib/rules/function-blacklist/README.md

**Comment by nex3** [comment]
No, that rule isn't aware of Sass's module syntax.

**Comment by kristerkari** [comment]
> No, that rule isn't aware of Sass's module syntax.

I see.

> Maybe a more general way to do this would be to have a lint that just takes a list of banned functions.

This seems like a good option to add in addition to the `function-blacklist` rule.
