### ISSUE TITLE
sass function not recognized

### ISSUE THREAD

**Issue by tanekim77** [stylelint-scss/stylelint-scss#494]
It seems stylelint-scss is not recognizing some of sass's built in functions, like map.merge. Or is it?

**Comment by kristerkari** [comment]
In what context not recognizing? Can you give an example?

**Comment by PhiLhoSoft** [comment]
I have a real example: on the line
`	box-shadow: 0 0 20px rgba(black, 0.15);
`
I get the error: `Expected modern color-function notation  color-function-notation`
I expect this plugin to relax the rule, here, since Sass converts it to a real CSS notation.

**Comment by XhmikosR** [comment]
Something seems wrong with your setup.
