### ISSUE TITLE
How to add comment automatically?

### ISSUE THREAD

**Issue by cacheMore** [stylelint-scss/stylelint-scss#545]
for example

```
.main {
  // .main-title
  &-title {
    font-size: 20px;
  }
}
```
I add the comment "// .main-title" manually, could it be done automatically? 
thanks.

**Comment by jeddy3** [comment]
> could it be done automatically?

Yes, you can [write a Stylelint plugin](https://stylelint.io/developer-guide/plugins) to do that.
