### ISSUE TITLE
no-global-function-names doesn't allow css filter declaration

### ISSUE THREAD

**Issue by bavarianbytes** [stylelint-scss/stylelint-scss#562]
`no-global-function-names` shows error for `backdrop-filter: saturate(140%) blur(10px);` cause of the `saturate`.
I think there should be exceptions for filter and backdrop-filter.

**Comment by kristerkari** [comment]
Thanks! I agree, it's something that should be improved in the rule.

**Comment by AleksandrHovhannisyan** [comment]
Also affects CSS's min function. That also triggers the `no-global-function-names` error.

**Comment by kristerkari** [comment]
> Also affects CSS's math functions. e.g., `min` also triggers the `no-global-function-names` error.

Yup, there is an issue open about it:
https://github.com/stylelint-scss/stylelint-scss/issues/486
