### ISSUE TITLE
Rename rules for blacklist and whitelist

### ISSUE THREAD

**Issue by stof** [stylelint-scss/stylelint-scss#571]
Stylelint 13.7 has renamed rules using `-whitelist` and `-blacklist` in their name (keeping the old rule names as deprecated until the next major version of course): https://stylelint.io/CHANGELOG#1370

It might make sense to do a similar change in stylelint-scss

**Comment by kristerkari** [comment]
Good catch! Makes sense to keep the naming in sync with stylelint.
