### ISSUE TITLE
False positive for operator-no-unspaced when setting unicode ranges

### ISSUE THREAD

**Issue by mirisuzanne** [stylelint-scss/stylelint-scss#576]
Unicode ranges take a form like `U+0000-00FF`, and should not have spacing internally. These values should not trigger the operator lint rules.

**Comment by kristerkari** [comment]
Thanks! Looks like a bug.

**Comment by kristerkari** [comment]
@mirisuzanne I had a look at the rule, and it ignores the `unicode-range` property. Is the error that you are getting related to saving those unicode ranges to variables?

**Comment by mirisuzanne** [comment]
Huh, I'm not sure why it was throwing - I can't reproduce this anymore. There must have been another issue confusing the parser. Closing.
