### ISSUE TITLE
Variable, mixin, and function pattern rules should not error on `_` prefix used for private sass contructs

### ISSUE THREAD

**Issue by mirisuzanne** [stylelint-scss/stylelint-scss#577]
Sass requires the `_` prefix as a consistent pattern to make variables, mixins, or function "private" to a particular module. That should be allowed even when the naming pattern does not otherwise allow underscores.

**Comment by kristerkari** [comment]
Thanks @mirisuzanne ! 

Isn't the idea of the "pattern" rules that you provide your own pattern to check against, or are you referring to using some ready made SCSS configs that have the pattern rules enabled?

**Comment by mirisuzanne** [comment]
Ah, you're right. This should be filed against [stylelint-scss/stylelint-config-standard-scss](https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/main/index.js#L25). I'll re-file the issue over there.
