### ISSUE TITLE
function-quote-no-quoted-strings-inside auto fix can corrupt code

### ISSUE THREAD

**Issue by aKzenT** [stylelint-scss/stylelint-scss#633]
Auto fix for function-quote-no-quoted-strings-inside changed this code:
```
        @if $template {
            $template: $template quote($area-row);
        }
        @else {
            $template: quote($area-row);
        }
```

To this code:
```
        @if $template {
            $template: $area-row;
        } @else {
            $template: $area-row;
        }
```

which corrupts the code of course.

The actual use case here is building up values for `grid-template-areas`. So $template later contains `"rowa" "rowb" "rowc"....`

**Comment by kristerkari** [comment]
Sounds like a bug!
