### ISSUE TITLE
Support end positions for warnings

### ISSUE THREAD

**Issue by ybiquitous** [stylelint-scss/stylelint-scss#652]
[Stylelint 14.7.0](https://github.com/stylelint/stylelint/releases/tag/14.7.0) has supported end positions for warnings, and the official VSCode extension [prepares the end position support](https://github.com/stylelint/vscode-stylelint/pull/358).

So, I suggest `stylelint-scss` also supports end positions.

Currently, `stylelint-scss` warns for the whole node, but it seems not good DX:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/473530/185413438-50ea0ad6-0d5f-4d8b-91b7-fb603b37b819.png">

<details>
<summary>Reproduction Details</summary>

`package.json`:

```json
{
  "dependencies": {
    "postcss-scss": "4.0.4",
    "stylelint": "14.10.0",
    "stylelint-codeframe-formatter": "1.1.0",
    "stylelint-scss": "4.3.0"
  },
  "scripts": {
    "test": "stylelint \"*.scss\" --custom-formatter stylelint-codeframe-formatter"
  }
}
```

`.stylelintrc.js`:

```js
module.exports = {
  plugins: ["stylelint-scss"],
  customSyntax: "postcss-scss",
  rules: {
    "scss/at-rule-no-unknown": true,
    "scss/at-if-no-null": true,
  },
};
```

`a.scss`:

```scss
@foo {
  // ...
}

a {
  @if $x == null {}
}
```

</details>

---

This will change many files (maybe all rules), but I can help from [my experience in the stylelint/stylelint repo](https://github.com/stylelint/stylelint/issues/5694).

**Comment by kristerkari** [comment]
Thanks! This would definitely be a good improvement! :)

**Comment by ybiquitous** [comment]
@kristerkari Thanks for the response. It seems this task needs many PRs, so I create the following list to make the progress clear:

- [ ] [at-each-key-value-single-line](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-each-key-value-single-line)
- [ ] [at-else-closing-brace-newline-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-else-closing-brace-newline-after)
- [ ] [at-else-closing-brace-space-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-else-closing-brace-space-after)
- [ ] [at-else-empty-line-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-else-empty-line-before)
- [ ] [at-else-if-parentheses-space-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-else-if-parentheses-space-before)
- [ ] [at-extend-no-missing-placeholder](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-extend-no-missing-placeholder)
- [ ] [at-function-named-arguments](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-function-named-arguments)
- [ ] [at-function-parentheses-space-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-function-parentheses-space-before)
- [ ] [at-function-pattern](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-function-pattern)
- [ ] [at-if-closing-brace-newline-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-if-closing-brace-newline-after)
- [ ] [at-if-closing-brace-space-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-if-closing-brace-space-after)
- [ ] [at-if-no-null](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-if-no-null)
- [ ] [at-import-no-partial-leading-underscore](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-import-no-partial-leading-underscore)
- [ ] [at-import-partial-extension-blacklist](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-import-partial-extension-blacklist)
- [ ] [at-import-partial-extension-whitelist](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-import-partial-extension-whitelist)
- [ ] [at-import-partial-extension](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-import-partial-extension)
- [ ] [at-mixin-argumentless-call-parentheses](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-mixin-argumentless-call-parentheses)
- [ ] [at-mixin-named-arguments](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-mixin-named-arguments)
- [ ] [at-mixin-parentheses-space-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-mixin-parentheses-space-before)
- [ ] [at-mixin-pattern](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-mixin-pattern)
- [ ] [at-rule-conditional-no-parentheses](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-rule-conditional-no-parentheses)
- [ ] [at-rule-no-unknown](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-rule-no-unknown)
- [ ] [at-use-no-unnamespaced](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/at-use-no-unnamespaced)
- [ ] [comment-no-empty](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/comment-no-empty)
- [ ] [comment-no-loud](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/comment-no-loud)
- [ ] [declaration-nested-properties-no-divided-groups](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/declaration-nested-properties-no-divided-groups)
- [ ] [declaration-nested-properties](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/declaration-nested-properties)
- [ ] [dimension-no-non-numeric-values](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dimension-no-non-numeric-values)
- [ ] [dollar-variable-colon-newline-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-colon-newline-after)
- [ ] [dollar-variable-colon-space-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-colon-space-after)
- [ ] [dollar-variable-colon-space-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-colon-space-before)
- [ ] [dollar-variable-default](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-default)
- [ ] [dollar-variable-empty-line-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-empty-line-after)
- [ ] [dollar-variable-empty-line-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-empty-line-before)
- [ ] [dollar-variable-first-in-block](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-first-in-block)
- [ ] [dollar-variable-no-missing-interpolation](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-no-missing-interpolation)
- [ ] [dollar-variable-no-namespaced-assignment](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-no-namespaced-assignment)
- [ ] [dollar-variable-pattern](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/dollar-variable-pattern)
- [ ] [double-slash-comment-empty-line-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/double-slash-comment-empty-line-before)
- [ ] [double-slash-comment-inline](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/double-slash-comment-inline)
- [ ] [double-slash-comment-whitespace-inside](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/double-slash-comment-whitespace-inside)
- [ ] [function-color-relative](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-color-relative)
- [ ] [function-no-unknown](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown)
- [ ] [function-quote-no-quoted-strings-inside](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-quote-no-quoted-strings-inside)
- [ ] [function-unquote-no-unquoted-strings-inside](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-unquote-no-unquoted-strings-inside)
- [ ] [map-keys-quotes](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/map-keys-quotes)
- [ ] [media-feature-value-dollar-variable](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/media-feature-value-dollar-variable)
- [ ] [no-dollar-variables](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/no-dollar-variables)
- [ ] [no-duplicate-dollar-variables](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/no-duplicate-dollar-variables)
- [ ] [no-duplicate-mixins](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/no-duplicate-mixins)
- [ ] [no-global-function-names](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/no-global-function-names)
- [ ] [operator-no-newline-after](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/operator-no-newline-after)
- [ ] [operator-no-newline-before](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/operator-no-newline-before)
- [ ] [operator-no-unspaced](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/operator-no-unspaced)
- [ ] [partial-no-import](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/partial-no-import)
- [ ] [percent-placeholder-pattern](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/percent-placeholder-pattern)
- [ ] [selector-nest-combinators](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/selector-nest-combinators)
- [ ] [selector-no-redundant-nesting-selector](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/selector-no-redundant-nesting-selector)
- [ ] [selector-no-union-class-name](https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/selector-no-union-class-name)

**Comment by ybiquitous** [comment]
I've made one PR #655 to make subsequent PRs easier.

**Comment by kristerkari** [comment]
@ ybiquitous  Thanks a ton for the PRs. It really is a lot of work for you to migrate the rules :)

**Comment by ybiquitous** [comment]
Yeah, I've done more than half of the rules for now. I'll complete this issue within a few weeks. 👌🏼

**Comment by ybiquitous** [comment]
I've created Pull Requests for all the rules!

**Comment by kristerkari** [comment]
Thanks again! All merged now. :)

**Comment by ybiquitous** [comment]
Thanks for merging all! I'm closing this issue.
