### ISSUE TITLE
Broken link for `at-extend-no-missing-placeholder` documentation

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint-scss/stylelint-scss#661]
The current version: https://github.com/stylelint-scss/stylelint-scss/blob/1d61559/src/rules/at-extend-no-missing-placeholder/README.md

Problematic place:

> See [Mastering Sass extends and placeholders](http://8gramgorilla.com/mastering-sass-extends-and-placeholders/).

Tests:

https://www.uptimia.com/website-availability-test/a5d71e60

![image](https://user-images.githubusercontent.com/6510020/188023735-ea7bedc7-d155-425a-8755-84e4ced29907.png)

https://www.internetvista.com/en/test-your-website.htm

![image](https://user-images.githubusercontent.com/6510020/188023758-6b9cc0dc-c25b-450c-a03d-9dec8a0ed925.png)

**Comment by XhmikosR** [comment]
The link was removed from the docs.

**Comment by AlexWayfer** [comment]
No replacement? Even [WebArchive](https://web.archive.org/web/20220811153352/http://8gramgorilla.com/mastering-sass-extends-and-placeholders/)? OK.

**Comment by XhmikosR** [comment]
If you have a suggestion you can always submit a PR yourself.
