### ISSUE TITLE
replace -blacklist/-whitelist  configuration entries to inclusive ones

### ISSUE THREAD

**Issue by MauricioMCosta** [stylelint-scss/stylelint-scss#819]
Project stylelint, has made these changes deprecating config entries ending with -blacklist/-whitelist and using more inclusive terms -disallowed-list/allowed-list.

These terms are becoming offending terms in some software scanners.

**Comment by kristerkari** [comment]
There's already an open issue for this: https://github.com/stylelint-scss/stylelint-scss/issues/571
