### ISSUE TITLE
dollar-variable-colon-space-after incorrect

### ISSUE THREAD

**Issue by amk221** [stylelint-scss/stylelint-scss#845]
When prettier formats the rules like in the below screenshot, the space after the colon isn't required

<img width="647" alt="Screenshot 2023-08-04 at 23 24 32" src="https://github.com/stylelint-scss/stylelint-scss/assets/382061/66029020-a754-46e9-b354-9447bbfbcaaa">
<img width="742" alt="Screenshot 2023-08-04 at 23 25 21" src="https://github.com/stylelint-scss/stylelint-scss/assets/382061/986ce558-a45e-488c-87e0-d43f8546d793">

**Comment by kristerkari** [comment]
@amk221  I check how the rule works, and it looks that it's actually like that by design, and you need to use the `"always-single-line"` option to allow that syntax. 

Let me know if that does not help!
