### ISSUE TITLE
Support individual findings for code review toolings

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint-scss/stylelint-scss#856]
Code review toolings, such as Github API or Google's internal lint checks, often require linters to provide a fix for each finding individually rather than fixing all findings in the entire file. Stylelint doesn't support such feature as it can only fix the entire file with `--fix`, therefore it is not able to fix just one finding or to limit its changes to a region in a file.

**Comment by nex3** [comment]
This has been re-filed as https://github.com/stylelint/stylelint/issues/7192#issuecomment-1726698251, so this issue can probably be closed out.
