### ISSUE TITLE
Deprecate `at-import-no-partial-leading-underscore` and add `load-no-partial-leading-underscore`.

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint-scss/stylelint-scss#859]
The same rules in [at-import-no-partial-leading-underscore](https://g3doc.corp.google.com/third_party/javascript/node_modules/stylelint_scss/v5_2_1/src/rules/at-import-no-partial-leading-underscore/README.md?cl=head) of disallowing leading underscores and file extensions apply to [@use](https://sass-lang.com/documentation/at-rules/use/), [@forward](https://sass-lang.com/documentation/at-rules/forward/) and [meta.load-css()](https://sass-lang.com/documentation/modules/meta/#mixins) url parameter. The existing `at-import-no-partial-leading-underscore` rule could be expanded to cover all these cases and then be renamed to `load-no-partial-leading-underscore`.

**Comment by kristerkari** [comment]
@pamelalozano16 sorry if I have not been clear about it, but we can not just rename rules if people are already using them in their projects and configs.

I think that the correct way of renaming something would be to [deprecate the rule](https://stylelint.io/developer-guide/rules#deprecate-a-rule), and then create a new rule to replace the old one.

**Comment by pamelalozano16** [comment]
@kristerkari Thanks for the clarification! :) Just updated the PR to the deprecation of `at-import-no-partial-leading-underscore` and adding `load-no-partial-leading-underscore` as a new rule.

**Comment by kristerkari** [comment]
Thanks! I'll review and create a new release as soon as I've merged the PRs for the new rules.

**Comment by jelly** [comment]
I believe this rule now breaks a normal run of stylelint, as 5.3.0 was released but `stylelint-config-recommended-scss` still enables this rule by default. So every stylelint invocation will error out. So I have to set:

```
scss/at-import-no-partial-leading-underscore: null
```

In my config to disable the old rule and enabled the new one as likely that should be enabled in 

```
      "scss/at-import-no-partial-leading-underscore": null,
       "scss/load-no-partial-leading-underscore": true,
```

**Comment by pamelalozano16** [comment]
Hi @jelly! Thanks for reaching out. I tried replicating the error in [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBLAtgBwgJwC4AIAdEDAQ1wAsB6AfQDMHiBuQgOyQFcBnGIkKOlQZ1iAGj40AjADouYLl2ZskdHAHdS2KHzKVC+wvUYgm+KgCp8AdRSsoENV3ywANuhS4Y2J+arLuvMRcpArwaDC4pEqsbNKk+MBs+PiorGAuHLD44ZHSLhCkUAC08lwAFMRGIiDiACRqHhTw+BUgAEY4sNglEKy42CG4xM39HDAAlOMsrAC+bDUgdCguMABypOEIIDAAHhsYK7KlC5CsSwDmW4msycS7nnaKCPgA2knJfFy4AJ4rbn09M4oc5FL6kOyaYpyBTEd4AXVE72I2A4KyezWuH0+pSo+UKRVYECKZDwKFILiKK0KthBHDsXjkOBgw3wo2ZN3wc1mJ16FwAYjg0OQtgArLi9BawDBcK5IkBfX4wf5DZ7EFzkGBfMRyhV-Wy4QEXUGRCFaUGlFlqjVakBsGYgGZAA) but it is not breaking for me just showing the error twice. E.g.:
```
ERROR
Unexpected leading underscore in imported partial name
[(scss/load-no-partial-leading-underscore)](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/load-no-partial-leading-underscore)

ERROR
Unexpected leading underscore in imported partial name
[(scss/at-import-no-partial-leading-underscore)](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/at-import-no-partial-leading-underscore)
```

Could you please provide an example with the error so we can address it?
