### ISSUE TITLE
declaration-property-value-no-unknown for SCSS nested properties.

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint-scss/stylelint-scss#882]
Rule [declaration-property-value-no-unknown](https://github.com/stylelint/stylelint/tree/main/lib/rules/declaration-property-value-no-unknown) doesn't work for [SCSS nested properties](https://sass-lang.com/documentation/style-rules/declarations/#nesting). So `font-size: red;` raises an error, but `font: { size: red; }` does not. 

[Demo here](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AjABMAOgO0wFwHcALASzxngx33wGcAHAQzArRQgCdYOBadgDwDc1PAF9quPADMI2PJSyS6JAF6sOMKMMnjck4mRg8GzVuy4xeA7fhlzjq9Zu26cIADQgpJADYwAcowAtnCIMPzB9H5ItGC0tB7gst4A5gggimhomCDh5NhQtDmUANo4WVk5tHgAnn4+JPaQ2KnGeIwFjFzGcUUg5WgAuu4DORwArn59CgOVILBgPl2MeCSyPPQcEPSWtTwAbow+40bYEDzj2ADWZwS4CGh4EzADuqKJzakAYpxBK+kAK1oskSsHoCUQmWyIGqdRgDTkxWhS3I1RyI2wc1h9UaeB4nxIKTaHSgXSgPXiSJyKJgaP62HeoiAA).

**Comment by kristerkari** [comment]
It's very understandable that the stylelint rules don't support the nested properties, but I was wondering if there would be a better way to add the nested property support to those rules than just duplicating them in this library.

I've been trying to avoid the mirroring of rules from the stylelint core repo, but sometimes it has been the only sensible way to make the rule work with SCSS.

**Comment by pamelalozano16** [comment]
Following [the discussion](https://github.com/stylelint/stylelint/issues/7310#issuecomment-1800034082) with @jeddy3 in the Stylelint core repository, and recognizing that discouraging the use of nested properties is not a viable option due to its significance as one of the valuable features of SCSS, I agree that we should mirror the rule in `stylelint/scss` and provide support for nested properties. Let me know your thoughts, @kristerkari, and if you're on board with the idea, I can take care of the implementation. :)

**Comment by kristerkari** [comment]
@pamelalozano16 well, I don't like the idea of mirring rules, but I guess that it's the only option that we have to fully support the Sass syntax.

Just remember to ping me when you have something ready 👍
