### ISSUE TITLE
[Rule idea] Forbid defining unused private members

### ISSUE THREAD

**Issue by stof** [stylelint-scss/stylelint-scss#884]
Private members (i.e. functions, mixins, variables and selector placeholders) are not exposed outside the module boundary. so if they are not used inside the module, they are unused.

In Sass, private members have a name that start with either `-` or `_` (for variables, this comes after the `$` as the `$` is not considered to be part of the name. Same for the `%` prefix of selector placeholders).

This rule should check for usages in the same file. Projects that are still using `@import` rather than the module-aware `@use` and `@forward` are expected to keep this rule disabled (as all files loaded through `@import` are loaded inside the same module, which makes it impossible to ensure we see all usages of private members).

**Comment by kristerkari** [comment]
Sounds like a good idea!
