### ISSUE TITLE
Support stylelint16

### ISSUE THREAD

**Issue by newives** [stylelint-scss/stylelint-scss#894]
Support stylelint16 https://stylelint.io/migration-guide/to-16/

**Comment by newives** [comment]
Related questions: https://github.com/stylelint/stylelint/issues/7322#issuecomment-1810417821

**Comment by kristerkari** [comment]
@newives yes, definitely need to look into the breaking changes and what to do to support the new version.

I'm going to be quite busy tomorrow (Saturday), so I might not have time to look at it before Sunday.

**Comment by kristerkari** [comment]
I had a quick try at migrating to stylelint 16, but I think that there is something that I need to change related to the commonjs imports from stylelint (the ESM migration needs to done separately).

Here's the Git branch with the changes, in case anyone is interested to have a look and point me in the right direction:
https://github.com/stylelint-scss/stylelint-scss/tree/stylelint-v16
